# Exercise 2: numpy

In [1]:
import numpy as np

## Problem 1: 

Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **matrix** objects

In [4]:
################
# your solution
################
import numpy as np
A = np.matrix([[3, 2, 1],[6, -3, 0],[1, 2, 9]])
B = np.matrix([[-4, 1],[7, 3],[2, 5]])
C = A*B

print(C)

[[  4  14]
 [-45  -3]
 [ 28  52]]


Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **array** objects

In [6]:
D = np.array([[3, 2, 1],[6, -3, 0],[1, 2, 9]])
E = np.array([[-4, 1],[7, 3],[2, 5]])
F = D@E

print(F)

[[  4  14]
 [-45  -3]
 [ 28  52]]


## Problem 2: 

Numpy provides random number generators for different distributions.
You can find simple examples at [https://numpy.org/doc/stable/reference/random/index.html](https://numpy.org/doc/stable/reference/random/index.html)

1. Write a function that outputs a list of 250 numbers in a normal distribution with (approximately) mean of 2.5 and standard deviation of 0.75. (check [https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal))
2. Write a loop that uses this function to create 10 instances of such lists. Compute the actual mean and standard deviation and print them.
3. Verify that the answers are indeed random by running your code multiple times.

In [1]:
################
# your solution
################


## Problem 3: 

1. Compute and print the eigenvalues, $\lambda_i$, and eigenvectors, ${\bf n}_i$, of
$$
   {\bf A} =
   \left[ \begin{array}{ccccc}
   3 & 2 & 1 & 0 & 0 \\
   2 & 3 & 2 & 1 & 0 \\
   1 & 2 & 3 & 2 & 1 \\
   0 & 1 & 2 & 3 & 2 \\
   0 & 0 & 1 & 2 & 3 
   \end{array} \right]
$$
2. Show that
$$
   {\rm det}({\bf A}) = \prod_{i=1}^5 \lambda_i
$$
3. Verify the following relation
$$
   {\bf A} = \sum_{i=1}^{5} \lambda_i\,{\bf n}_i\otimes{\bf n}_i
$$

In [2]:
################
# your solution
################
import numpy as np
from numpy.linalg import solve

A=np.array([[3,2,1,0,0],[2,3,2,1,0],[1,2,3,2,1],[0,1,2,3,2],[0,0,1,2,3]])
(lam,vec)=np.linalg.eig(A)
lam

array([7.65427349, 4.56155281, 1.74770274, 0.43844719, 0.59802377])

In [11]:
np.linalg.det(A)-np.prod(lam)

83.0

In [15]:
Arep=sum(lam*np.outer(A,A))

ValueError: operands could not be broadcast together with shapes (5,) (25,25) 

16.000000000000036